#!/bin/sh

# from /etc/skel/.xinitrc
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge $HOME/.Xresources

for i in {1..3}; do
  xrandr -q | grep "DP${i} connected" && xrandr --output LVDS1 --off --output DP${i} --auto
  xrandr -q | grep "HDMI${i} connected" && xrandr --output LVDS1 --off --output HDMI${i} --auto
done

urxvtd -q -o -f

autocutsel -fork &

unclutter -noevents -root &

twmnd &

setxkbmap -rules evdev -model pc104 -layout us -variant altgr-intl -option ctrl:nocaps

exec i3
