#!/bin/sh

# from /etc/skel/.xinitrc
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge $HOME/.Xresources

xrandr -q | grep "DP1 connected" && xrandr --output LVDS1 --off --output DP1 --auto
xrandr -q | grep "HDMI1 connected" && xrandr --output LVDS1 --off --output HDMI1 --auto
xrandr -q | grep "DP2 connected" && xrandr --output LVDS1 --off --output DP2 --auto

urxvtd -q -o -f

autocutsel -fork &

unclutter -noevents -root &

pulseaudio --start

exec i3
